name: Notion Task Sync

on:
  push:
    branches:
      - "staging/**"
      - "feature/**"
      - "hotfix/**"
  pull_request:
    branches:
      - "staging/**"
      - "feature/**"
      - "hotfix/**"
    types:
      - opened
      - reopened
      - synchronize
      - closed
  workflow_dispatch:

permissions:
  contents: read
  issues: read

jobs:
  sync-tasks:
    name: Sync GitHub tasks to Notion
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TASK_DB_ID: ${{ secrets[vars.TASK_DB_SECRET_NAME] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Synchronise task issues with Notion
        env:
          TASK_DB_ID: ${{ env.TASK_DB_ID }}
        run: |
          if [ -z "${TASK_DB_ID}" ]; then
            echo "Task database secret is not configured; skipping sync."
            exit 0
          fi
          python -m agent_logic.notion_sync.workflow_sync \
            --entity tasks \
            --database-id "${TASK_DB_ID}" \
            --repository "${GITHUB_REPOSITORY}"
