name: Notion Project Sync

on:
  push:
    branches:
      - "staging/**"
      - "feature/**"
      - "hotfix/**"
  workflow_dispatch:

permissions:
  contents: read
  projects: read

jobs:
  sync-projects:
    name: Sync GitHub projects to Notion
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PROJECTS_DB_ID: ${{ secrets[vars.PROJECTS_DB_SECRET_NAME] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Synchronise projects with Notion
        env:
          PROJECTS_DB_ID: ${{ env.PROJECTS_DB_ID }}
        run: |
          if [ -z "${PROJECTS_DB_ID}" ]; then
            echo "Projects database secret is not configured; skipping sync."
            exit 0
          fi
          python -m agent_logic.notion_sync.workflow_sync \
            --entity projects \
            --database-id "${PROJECTS_DB_ID}" \
            --repository "${GITHUB_REPOSITORY}"
