name: Sync Workflow Runs to Notion

on:
  workflow_run:
    workflows:
      - Sync Tasks to Notion
      - Sync Pull Requests to Notion
      - Sync Issues to Notion
      - Sync Projects to Notion
      - Notion Synchronisation Pipeline
      - docker-compose
      - docker-hub-update
      - maintenance
      - tfc-sync
      - verify-env-vars
    types:
      - completed

permissions:
  contents: read

jobs:
  sync:
    name: Publish workflow run result to Notion
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'skipped' || github.event.workflow_run.status == 'completed' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run workflow log synchronisation
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_RUNS_BOARD_ID: ${{ secrets.NOTION_RUNS_BOARD_ID }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_RUN_ID_PROPERTY: ${{ vars.NOTION_RUN_ID_PROPERTY }}
        run: |
          python -m agent_logic.notion_sync.run_jobs runs --log-level INFO
