name: Notion Issue Sync

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned
  workflow_dispatch:

permissions:
  contents: read
  issues: read

jobs:
  sync:
    name: Sync issues database
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Synchronise issues with Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.AGENT_ACTIONS != '' && secrets.AGENT_ACTIONS || secrets.GITHUB_TOKEN }}
          ISSUE_DATABASE_ID: ${{ secrets.NOTION_ISSUES_DB_ID != '' && secrets.NOTION_ISSUES_DB_ID || vars.ISSUE_DATABASE_ID }}
          ISSUE_UNIQUE_PROPERTY: ${{ vars.ISSUE_UNIQUE_PROPERTY || 'GitHub ID' }}
        run: |
          if [ -z "$NOTION_TOKEN" ]; then
            echo "::error::NOTION_TOKEN secret is not configured."
            exit 1
          fi
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "::error::GITHUB_TOKEN secret is not configured."
            exit 1
          fi
          if [ -z "$ISSUE_DATABASE_ID" ]; then
            echo "::error::Issue database identifier is not configured."
            exit 1
          fi
          python -m agent_logic.notion_sync.entity_cli issues \
            --database-id "$ISSUE_DATABASE_ID" \
            --unique-property "$ISSUE_UNIQUE_PROPERTY"
