name: Sync Pull Requests to Notion

on:
  push:
    branches:
      - "develop"
      - "feature/**"
      - "staging/**"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  sync:
    name: Publish pull request updates to Notion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pull request synchronisation
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_PR_DB_ID: ${{ secrets.NOTION_PR_DB_ID }}
          NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_PR_ID_PROPERTY: ${{ vars.NOTION_PR_ID_PROPERTY }}
        run: |
          python -m agent_logic.notion_sync.run_jobs pull_requests --log-level INFO
