name: Notion Project Sync

on:
  push:
    branches:
      - "staging/**"
  pull_request:
    branches:
      - "staging/**"

permissions:
  contents: read

jobs:
  sync:
    name: Mirror milestones and projects to Notion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync project data to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ coalesce(secrets.AGENT_COLLAB, secrets.GITHUB_TOKEN) }}
          NOTION_PROJECTS_DB_ID: ${{ secrets[format('%s_PROJECTS_DB_ID', coalesce(vars.AGENT_SECRET_PREFIX, 'A_00'))] }}
        run: |
          if [ -z "${NOTION_TOKEN}" ] || [ -z "${GITHUB_TOKEN}" ] || [ -z "${NOTION_PROJECTS_DB_ID}" ]; then
            echo "Required credentials not configured; skipping project sync."
            exit 0
          fi
          python -m agent_logic.notion_sync.entity_sync \
            --entity projects \
            --database-id "${NOTION_PROJECTS_DB_ID}" \
            --github-repo "${GITHUB_REPOSITORY}"
