name: Notion Runs Board Sync

on:
  workflow_run:
    workflows:
      - Build and Publish image to Docker Hub
      - maintenance
      - Notion Issue Sync
      - Notion Pull Request Sync
      - Notion Project Sync
      - Notion Synchronisation Pipeline
      - Notion Task Sync
      - tfc-sync
      - Verify Environment Variables
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  sync:
    name: Record workflow run in Notion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update runs board entry
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          RUNS_DATABASE_ID: ${{ secrets.NOTION_RUNS_BOARD_ID || vars.NOTION_RUNS_BOARD_ID }}
        run: |
          if [ -z "$RUNS_DATABASE_ID" ]; then
            echo "Runs board Notion database ID is not configured." >&2
            exit 1
          fi
          python -m agent_logic.notion_sync.entity_sync runs --database-id "$RUNS_DATABASE_ID" --verbose
