name: Notion Task Sync

on:
  push:
    branches:
      - "staging/**"
      - "dev/**"
      - "feature/**"
      - "hotfix/**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned
  workflow_dispatch:

permissions:
  contents: read
  issues: read
  pull-requests: read

concurrency:
  group: notion-task-sync-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync tasks to Notion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Synchronise tasks to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_TASK_DB_ID: ${{ secrets.A_TASK_DB_ID }}
          NOTION_SYNC_DRY_RUN: ${{ vars.NOTION_SYNC_DRY_RUN }}
        run: |
          if [ -z "${NOTION_TOKEN}" ] || [ -z "${GITHUB_TOKEN}" ] || [ -z "${NOTION_TASK_DB_ID}" ]; then
            echo "Notion task sync skipped because required secrets are not configured."
            exit 0
          fi
          DRY_RUN_FLAG=""
          if [ "${NOTION_SYNC_DRY_RUN}" = "true" ]; then
            DRY_RUN_FLAG="--dry-run"
          fi
          python -m agent_logic.notion_sync.sync_entities tasks \
            --database-id "${NOTION_TASK_DB_ID}" \
            --repo "${{ github.repository }}" \
            --unique-property "GitHub ID" \
            ${DRY_RUN_FLAG}
