name: Notion Task Sync

on:
  push:
    branches:
      - "staging/**"
  pull_request:
    branches:
      - "staging/**"

permissions:
  contents: read
  issues: read

jobs:
  sync:
    name: Mirror GitHub tasks to Notion
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync tasks to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ coalesce(secrets.AGENT_COLLAB, secrets.GITHUB_TOKEN) }}
          SECRET_PREFIX: ${{ coalesce(vars.AGENT_SECRET_PREFIX, 'A_00') }}
          NOTION_TASK_DB_ID: ${{ secrets[format('%s_TASK_DB_ID', coalesce(vars.AGENT_SECRET_PREFIX, 'A_00'))] }}
          TASK_LABELS: ${{ vars.TASK_LABELS }}
        run: |
          if [ -z "${NOTION_TOKEN}" ] || [ -z "${GITHUB_TOKEN}" ] || [ -z "${NOTION_TASK_DB_ID}" ]; then
            echo "Required credentials not configured; skipping task sync."
            exit 0
          fi
          python -m agent_logic.notion_sync.entity_sync \
            --entity tasks \
            --database-id "${NOTION_TASK_DB_ID}" \
            --github-repo "${GITHUB_REPOSITORY}" \
            --task-labels "${TASK_LABELS}"
