name: Notion Pull Request Sync

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  sync:
    name: Sync pull requests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Synchronise pull requests with Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.AGENT_ACTIONS != '' && secrets.AGENT_ACTIONS || secrets.GITHUB_TOKEN }}
          PR_DATABASE_ID: ${{ secrets.NOTION_PR_DB_ID != '' && secrets.NOTION_PR_DB_ID || vars.PR_DATABASE_ID }}
          PR_UNIQUE_PROPERTY: ${{ vars.PR_UNIQUE_PROPERTY || 'GitHub ID' }}
        run: |
          if [ -z "$NOTION_TOKEN" ]; then
            echo "::error::NOTION_TOKEN secret is not configured."
            exit 1
          fi
          if [ -z "$GITHUB_TOKEN" ]; then
            echo "::error::GITHUB_TOKEN secret is not configured."
            exit 1
          fi
          if [ -z "$PR_DATABASE_ID" ]; then
            echo "::error::Pull request database identifier is not configured."
            exit 1
          fi
          python -m agent_logic.notion_sync.entity_cli pull-requests \
            --database-id "$PR_DATABASE_ID" \
            --unique-property "$PR_UNIQUE_PROPERTY"
