name: Notion PR Sync

on:
  pull_request:
    branches:
      - "staging/**"
      - "feature/**"
      - "hotfix/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - converted_to_draft
      - closed
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  sync-prs:
    name: Sync pull requests to Notion
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_DB_ID: ${{ secrets[vars.PR_DB_SECRET_NAME] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Synchronise pull requests with Notion
        env:
          PR_DB_ID: ${{ env.PR_DB_ID }}
        run: |
          if [ -z "${PR_DB_ID}" ]; then
            echo "PR database secret is not configured; skipping sync."
            exit 0
          fi
          python -m agent_logic.notion_sync.workflow_sync \
            --entity pull_requests \
            --database-id "${PR_DB_ID}" \
            --repository "${GITHUB_REPOSITORY}"
