name: Notion Issues Sync

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - closed
      - assigned
      - unassigned
      - labeled
      - unlabeled
  workflow_dispatch:

permissions:
  contents: read
  issues: read

jobs:
  sync-issues:
    name: Sync GitHub issues to Notion
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUES_DB_ID: ${{ secrets[vars.ISSUES_DB_SECRET_NAME] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Synchronise issues with Notion
        env:
          ISSUES_DB_ID: ${{ env.ISSUES_DB_ID }}
        run: |
          if [ -z "${ISSUES_DB_ID}" ]; then
            echo "Issues database secret is not configured; skipping sync."
            exit 0
          fi
          python -m agent_logic.notion_sync.workflow_sync \
            --entity issues \
            --database-id "${ISSUES_DB_ID}" \
            --repository "${GITHUB_REPOSITORY}"
