name: Notion Issues Sync

on:
  issues:
    types:
      - opened
      - edited
      - closed
      - reopened
      - labeled
      - unlabeled
      - assigned
      - unassigned

permissions:
  contents: read
  issues: read

jobs:
  sync:
    name: Mirror GitHub issues to Notion
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync issues to Notion
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          GITHUB_TOKEN: ${{ coalesce(secrets.AGENT_COLLAB, secrets.GITHUB_TOKEN) }}
          NOTION_ISSUES_DB_ID: ${{ secrets[format('%s_ISSUES_DB_ID', coalesce(vars.AGENT_SECRET_PREFIX, 'A_00'))] }}
        run: |
          if [ -z "${NOTION_TOKEN}" ] || [ -z "${GITHUB_TOKEN}" ] || [ -z "${NOTION_ISSUES_DB_ID}" ]; then
            echo "Required credentials not configured; skipping issue sync."
            exit 0
          fi
          python -m agent_logic.notion_sync.entity_sync \
            --entity issues \
            --database-id "${NOTION_ISSUES_DB_ID}" \
            --github-repo "${GITHUB_REPOSITORY}"
