# Terraform Cloud workflow bridge for apply runs.
# Requires repo variables `TFC_ORGANIZATION`, `TFC_WORKSPACE` and secret `TFC_TOKEN`.
name: Terraform Cloud Apply Run

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '**/.terraform.lock.hcl'
      - '.terraform-version'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: terraform-cloud-apply-${{ github.ref }}
  cancel-in-progress: false

env:
  TF_CLOUD_ORGANIZATION: "${{ vars.TFC_ORGANIZATION }}"
  TF_API_TOKEN: "${{ secrets.TFC_TOKEN }}"
  TF_WORKSPACE: "${{ vars.TFC_WORKSPACE }}"
  CONFIG_DIRECTORY: "."

jobs:
  terraform-cloud-apply-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Upload configuration to Terraform Cloud
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Queue apply run in Terraform Cloud
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          message: "Apply run from GitHub Actions for ${{ github.sha }}"

      - name: Apply confirmed run in Terraform Cloud
        if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable }}
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Apply run from GitHub Actions for ${{ github.sha }}"
